### ISSUE TITLE
How do you actually run this?

### ISSUE THREAD

**Issue by srustamo** [ericsubach/stow-lite#1]
New to python and win. I use GNU Stow on other platforms.

**Comment by ericsubach** [comment]
I apologize, I haven't put any documentation here...this was just something I whipped up for myself. Just be aware this is barebones hacky substitute for GNU Stow.

You actually need to create a python script, instantiate an object of StowLiteWindows with your desired settings. It's been awhile since I used GNU Stow, but I think the concept of package and target dir are the same. Then invoke the run method on that object. Unfortunately, you will need to read the code if you want to know more.

**Comment by srustamo** [comment]
Thank you.
